# Generated by Django 2.2.6 on 2019-11-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('category', models.CharField(max_length=64)),
                ('count', models.IntegerField(default=1)),
                ('total_count', models.IntegerField(default=10, editable=False)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
                'ordering': ['name'],
            },
        ),
    ]
