# Generated by Django 2.2.6 on 2019-11-04 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20191104_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additionally',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.product'),
        ),
    ]
