# Generated by Django 2.2.6 on 2019-11-04 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_product_additionally'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additionally',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='menu.product'),
        ),
    ]
