# Generated by Django 2.2.6 on 2019-11-05 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20191105_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='additional',
        ),
        migrations.RemoveField(
            model_name='product',
            name='full_price',
        ),
    ]
