# Generated by Django 2.2.6 on 2019-10-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('all_count', models.IntegerField()),
                ('count', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
    ]
