# Generated by Django 2.2.6 on 2019-10-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('count', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=3, default=3, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='food_model',
        ),
    ]
