# Generated by Django 2.2.6 on 2019-10-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20191006_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_model',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
