# Generated by Django 2.2.6 on 2019-10-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0002_delete_food_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='food_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('all_count', models.IntegerField()),
                ('count', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
    ]
