# Generated by Django 2.2.6 on 2019-10-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20191011_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, default=3, max_digits=5)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='food',
            name='count',
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=5),
        ),
    ]
